### ISSUE TITLE
Questions about data

### ISSUE THREAD

**Issue by andreas-weise** [nlp-psych/emotion#1]
I have some difficulty understanding the content of and relationships between the different files. The "emobase2010.arff" is clear, by itself. It contains 1582 features and the label for each of 4851 instances. But I'm not sure which utterances these are exactly. It seems there are over 9000 transcribed in the "trans" folder, way more than 4851. "category.txt" in the "eval" folder has annotations for 6578 of those. It is not clear to me why the missing utterances were not annotated. "intensity.txt" in the same folder seems to contain further annotations for those 2847 utterances which received a majority label other than "NEU", among the 6578 in "category.txt". None of these numbers match the 4851 instances in the feature file or the 2743 left after filtering out "NEU", "UNK", and "OTH". How can I match the features to specific utterances in order to "Experiment with combining the labels" as the readme suggests?

**Comment by rivlev** [comment]
* There are transcriptions in the trans folder that do not correspond to wav files that we have. I don't know why they were not included in the distribution of the corpus that I have. The 4851 instances correspond to 8 of the wav files 
01_MAD_1.wav  01_MMK_1.wav  02_MTN.wav  03_FTY.wav  05_MYH.wav
01_MAD_2.wav  01_MMK_2.wav  03_FMA.wav  04_MNN.wav
* The arff file should contain instance names which allow you to look them up in the eval files. They were accidentally removed during processing (since python's arff reader can't handle string variables). Unfortunately I can't recover them easily, so I am regenerating the arff file and will upload when it is finished (tonight or tomorrow)

**Comment by rivlev** [comment]
The arff file has been updated. The string ids will need to be removed (using e.g. a vi regex) for python to be able to process the arff. Separately, instances.txt has the string ids corresponding to each instance in the arff file.

**Comment by andreas-weise** [comment]
The latest commit I see on the repository is 11 days old. Maybe you didn't push the update of the arff?

@rivlev

**Comment by rivlev** [comment]
sorry, the update failed because the file was too large. It's up now

**Comment by andreas-weise** [comment]
There is a weird issue with the file now that prevents it from loading even after removing the "name" attribute declaration and its values. In the new version of the file, only 9 possible values for the "class" attribute are declared. "ANT" and "UNK" are missing. Besides that, apparently all those instances which should have a "UNK" value for the class, instead have ", )" as the last attribute value. Both those things are easy fixes but they just seem weird and perhaps other things went wrong with the generation of this file that aren't as obvious?

There is also the fact that the current emobase2010.arff contains 4850 instances (one less than before!) and instances.txt contains 4855. It shouldn't be hard to compute our own instances.txt from the name attribute before deleting it. But again, perhaps this is an indication of other problems?

@rivlev

**Comment by andreas-weise** [comment]
I extracted the instance names from the arff file and compared them with instances.txt.
These are the five instances that appear only in the latter: 
03_FTY.215
04_MNN.777
04_MNN.267
04_MNN.417
01_MMK_1.178

At this point I can work with the data but anyone who doesn't notice this problem or read this issue will assign incorrect instance IDs to most of the feature vectors. Plus, perhaps there are other problems.

**Comment by rivlev** [comment]
Thanks for pointing that out. The arff instance names were written (more or less) atomically with the feature extraction so those can be relied on.
